#!/usr/bin/env bash

echo "Setting Git Defaults..."

git config --global user.email "chase.timmins@gmail.com"
git config --global user.name "Chase Timmins"
git config --global core.autocrlf false
git config --global init.defaultbranch "main"
git config --global push.autosetupremote true

echo ""
echo "Git Config set to the following:"

git config --global -l
