[font]
size = 12

[font.normal]
family = "Hasklug Nerd Font Mono"

[font.offset]
y = 0

[font.glyph_offset]
y = 0

[window]
opacity = 0.95
decorations = "full"
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 120
lines = 40


[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[scrolling]
history = 0
autoscroll = true

[terminal]
osc52 = "CopyPaste"

[colors.primary]
background = '0x122637'
foreground = '0xffffff'

[colors.cursor]
text = '0x122637'
cursor = '0xf0cb09'

[colors.normal]
black = '0x000000'
red = '0xff0000'
green = '0x37dd21'
yellow = '0xfee409'
blue = '0x1460d2'
magenta = '0xff005d'
cyan = '0x00bbbb'
white = '0xbbbbbb'

[colors.bright]
black = '0x545454'
red = '0xf40d17'
green = '0x3bcf1d'
yellow = '0xecc809'
blue = '0x5555ff'
magenta = '0xff55ff'
cyan = '0x6ae3f9'
white = '0xffffff'

