require('zfg.ext.colors')
require('zfg.ext.harpoon')
require('zfg.ext.lualine')
require("zfg.ext.nvim-tree")
require('zfg.ext.markdown-preview')
require('zfg.ext.mason')
require('zfg.ext.snip')
require('zfg.ext.startup')
require('zfg.ext.tabline')
require('zfg.ext.telescope')
require('zfg.ext.treesitter')
require('zfg.ext.undotree')

